modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="vampirismbalance"
version="1.0.0"
displayName="Vampirism Balance"
description='''
Балансировка рас вампиров и оборотней для мода Vampirism
'''
authors="Vladisss"

[[dependencies.vampirismbalance]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.vampirismbalance]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.vampirismbalance]]
modId="vampirism"
mandatory=true
versionRange="[1.10.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.vampirismbalance]]
modId="werewolves"
mandatory=true
versionRange="[1.10.0,)"
ordering="AFTER"
side="BOTH"
